.PHONY: clean All

All:
	@echo "----------Building project:[ debugs - Debug ]----------"
	@cd "debugs" && "$(MAKE)" -f  "debugs.mk"
clean:
	@echo "----------Cleaning project:[ debugs - Debug ]----------"
	@cd "debugs" && "$(MAKE)" -f  "debugs.mk" clean
