.PHONY: clean All

All:
	@echo "----------Building project:[ cppwithcherno - Debug ]----------"
	@cd "cppwithcherno" && "$(MAKE)" -f  "cppwithcherno.mk"
clean:
	@echo "----------Cleaning project:[ cppwithcherno - Debug ]----------"
	@cd "cppwithcherno" && "$(MAKE)" -f  "cppwithcherno.mk" clean
