.PHONY: clean All

All:
	@echo "----------Building project:[ learncpp - Debug ]----------"
	@cd "learncpp" && "$(MAKE)" -f  "learncpp.mk"
clean:
	@echo "----------Cleaning project:[ learncpp - Debug ]----------"
	@cd "learncpp" && "$(MAKE)" -f  "learncpp.mk" clean
