.PHONY: clean All

All:
	@echo "----------Building project:[ dfsgraph - Debug ]----------"
	@cd "dfsgraph" && "$(MAKE)" -f  "dfsgraph.mk"
clean:
	@echo "----------Cleaning project:[ dfsgraph - Debug ]----------"
	@cd "dfsgraph" && "$(MAKE)" -f  "dfsgraph.mk" clean
