.PHONY: clean All

All:
	@echo "----------Building project:[ tictactoe - Debug ]----------"
	@cd "tictactoe" && "$(MAKE)" -f  "tictactoe.mk"
clean:
	@echo "----------Cleaning project:[ tictactoe - Debug ]----------"
	@cd "tictactoe" && "$(MAKE)" -f  "tictactoe.mk" clean
