.PHONY: clean All

All:
	@echo "----------Building project:[ bitsofcppaday - Debug ]----------"
	@cd "bitsofcppaday" && "$(MAKE)" -f  "bitsofcppaday.mk"
clean:
	@echo "----------Cleaning project:[ bitsofcppaday - Debug ]----------"
	@cd "bitsofcppaday" && "$(MAKE)" -f  "bitsofcppaday.mk" clean
